FROM python:3.9-slim-buster

ARG HTC_USER

RUN apt-get update && \
    apt-get -y install --no-install-recommends gcc g++ python3-pip && \
    pip3 install --upgrade pip && \
    useradd -r -m -u 1000 ${HTC_USER} && \
    chown -R htc: /home/${HTC_USER}/
